spring.application.name=Email-Writer-sb

gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-flash-latest:generateContent?key=
gemini.api.key=AIzaSyBs_ycsfLxJjiGPbjC7kxctbhO4D87ktNQ